[package]
name = "mprober-lib"
version = "0.1.15"
authors = ["Magic Len <len@magiclen.org>"]
edition = "2024"
rust-version = "1.89"
repository = "https://github.com/magiclen/m-prober-lib"
homepage = "https://magiclen.org/m-prober-lib"
keywords = ["linux", "probe", "proc"]
categories = ["os::unix-apis"]
description = "A library aims to quickly collect Linux system information including hostname, kernel version, uptime, RTC time, load average, CPU, memory, network interfaces, block devices and processes."
license = "MIT"
include = ["src/**/*", "Cargo.toml", "README.md", "LICENSE"]

[dependencies]
libc = "0.2"
scanner-rust = "3"
chrono = { version = "0.4", default-features = false, features = ["std"] }
serde = { version = "1", features = ["derive"], optional = true }

[features]
default = []
serde = ["dep:serde", "chrono/serde"]

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]

[dev-dependencies]
bencher = "0.1.5"

[[bench]]
name = "bench"
harness = false
